var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(d){var g=0;return function(){return g<d.length?{done:!1,value:d[g++]}:{done:!0}}};$jscomp.arrayIterator=function(d){return{next:$jscomp.arrayIteratorImpl(d)}};$jscomp.makeIterator=function(d){var g="undefined"!=typeof Symbol&&Symbol.iterator&&d[Symbol.iterator];if(g)return g.call(d);if("number"==typeof d.length)return $jscomp.arrayIterator(d);throw Error(String(d)+" is not an iterable or ArrayLike");};
$jscomp.arrayFromIterator=function(d){for(var g,h=[];!(g=d.next()).done;)h.push(g.value);return h};$jscomp.arrayFromIterable=function(d){return d instanceof Array?d:$jscomp.arrayFromIterator($jscomp.makeIterator(d))};
$(document).ready(function(){function d(a){var b;document.cookie.split(";").filter(function(c){c=c.trim().split("=");a===c[0]&&(b=c[1])});return b}function g(a,b,c){a.length&&Swal.queue(a).then(function(e){var m=[];e.value.forEach(function(f,n){!0===f&&(m[n]=b[n])});$.ajax({url:c.general.url.trim()+"modules/app",type:"POST",data:{action:"setSeenBrodcast",idsList:m,ip:l.ip,client_id:l.client_id,current_page:c.general.current_page},success:function(f){(f=d("bc_seen"))?(f=f.split(","),f=new Set([].concat($jscomp.arrayFromIterable(f),
$jscomp.arrayFromIterable(m))),f=[].concat($jscomp.arrayFromIterable(f)).join(","),f=f.toString()):f=m.toString();(new Date).getTime();var n=(new Date(Date.now()+864E5)).toUTCString();document.cookie="bc_seen="+f+";expires="+n+";path=/"}})})}var h=JSON.parse(window.siteData),l=JSON.parse(window.userData),k=h.general.current_page,p={},q={};(function(){$.ajax({url:h.general.url.trim()+"modules/app",type:"POST",data:{action:"getAllBroadCasts",page:h.general.current_page},success:function(a){a=JSON.parse(a);
p=a.broadCasts;q=a.bc_ids;g(p,q,h)}})})();$("#loginButton").click(function(a){a.preventDefault();$(".loginForm").submit();$(this).attr("disabled",!0);setTimeout(function(){$(this).attr("disabled",!1)},1E4)});if("addfunds"===k){var r=function(a){$.ajax({type:"POST",url:"addfunds",data:{selectedMethod:a,action:"getFields"},success:function(b){b=JSON.parse(b);$("#amount_field").html(b.inputs);$("#button_field").html(b.buttons)}})},u=$("#payment_method_new").val();r(u);$("#payment_method_new").on("change",
function(a){a.preventDefault();a=$(this).val();r(a)})}if("tickets"===k){var t=function(a){$.ajax({type:"POST",url:"tickets",data:{selectedOption:a,action:"getFields"},success:function(b){b=JSON.parse(b);$("#ticketsData").html(b)}})};k=$("#subject").val();t(k);$("#subject").on("change",function(){var a=$("#subject").val();t(a)})}$(".cancel-button").click(function(a){a.preventDefault();var b=$(this).attr("data-order-id");$.ajax({url:"orders/cancel/"+b,type:"POST",success:function(c){c=JSON.parse(c);
console.log(c);"success"===c.refill_icon&&$(".cancel-button[data-order-id="+b+"]").replaceWith("Cancelling");Swal.fire(c.refill_res,"",c.refill_icon)}})});$(".refill-button").click(function(a){a.preventDefault();if(!$(this).hasClass("disabled")){var b=$(this).attr("data-order-id");$.ajax({url:"orders/refill/"+b,type:"POST",success:function(c){c=JSON.parse(c);"success"==c.refill_icon?$(".refill-button[data-order-id="+b+"]").replaceWith("Refilling"):Swal.fire(c.refill_res,"",c.refill_icon)}})}});$("#phonepeQRSubmit").click(function(a){a.preventDefault();
$("#phonepeQRSubmit").prop("disabled",!0);a=$("#payment_amount").val();var b=$("#phonepeqr_orderid").val(),c=$("#payment_type").val();$("#loadderr").show();$("#phonepeForm").hide();$.ajax({url:"payment",type:"POST",data:{action:"phonepeQr",payment_amount:a,phonepeqr_orderid:b,payment_type:c},success:function(e){$("#loadderr").hide();$("#phonepeForm").show();e=JSON.parse(e);(new swal(e.title,"",e.icon)).then(function(m){"Payment Added Succesfully!"==e.title?($("#phonepeForm").trigger("reset"),window.location.href=
window.location.href):$("#phonepeQRSubmit").prop("disabled",!1)})}})});14==$("#payment_method option:selected").val()&&($("#paytmQrDiv").show(),$("#phonepeQrDiv").hide(),$("#amountInput").hide(),$("#submitButton").hide());31==$("#payment_method option:selected").val()&&($("#paytmQrDiv").hide(),$("#phonepeQrDiv").show(),$("#amountInput").hide(),$("#submitButton").hide());$("#payment_method").on("change",function(){14==this.value?($("#paytmQrDiv").show(),$("#phonepeQrDiv").hide(),$("#amountInput").hide(),
$("#submitButton").hide()):($("#phonepeQrDiv").hide(),$("#paytmQrDiv").hide(),$("#amountInput").show(),$("#submitButton").show());31==this.value&&($("#phonepeQrDiv").show(),$("#paytmQrDiv").hide(),$("#amountInput").hide(),$("#submitButton").hide())});$("#cancel_button").click(function(a){a.preventDefault();a=$("#order_id").val();$.ajax({url:"orders",type:"POST",data:{cancel_order:"cancel_order",order_id:a},beforeSend:function(){new swal({title:"Adding a cancellation request......",text:"Please wait for 2 seconds..",
showConfirmButton:!1})},success:function(b){b=JSON.parse(b);(new swal(b.title,"",b.icon)).then(function(c){window.location.href=window.location.href})}})});$("#updateEmail").click(function(a){a.preventDefault();a=$("#current_email").val();var b=$("#new_email").val(),c=$("#current_password").val();$.ajax({url:"confirm_email",type:"POST",data:{action:"change_email",current_email:a,new_email:b,current_password:c},beforeSend:function(){new swal({title:"Loading......",text:"Please wait for 2 seconds..",
showConfirmButton:!1})},success:function(e){e=JSON.parse(e);(new swal(e.title,"",e.icon)).then(function(m){"success"==e.icon&&($("#changeEmailModal").modal("hide"),window.location.href=window.location.href)})}})});$("#resend_verification_link").click(function(a){a.preventDefault();$.ajax({url:"confirm_email",type:"POST",data:{action:"resend_verification_link"},beforeSend:function(){new swal({title:"Loading......",text:"Please wait for 2 seconds..",showConfirmButton:!1})},success:function(b){b=JSON.parse(b);
(new swal(b.title,"",b.icon)).then(function(c){"success"==b.icon&&(window.location.href=window.location.href)})}})})});function submitPoll(){setTimeout(function(){document.getElementById("neworderbutton").disabled=!0},200);setTimeout(function(){document.getElementById("neworderbutton").disabled=!1},5E3)}$("#neworderbutton").click(function(){submitPoll()});
function showWhatsapp(d){(function(){var g={whatsapp:d,call_to_action:"Message us",position:"right"},h=document.location.protocol,l=h+"//static.getbutton.io",k=document.createElement("script");k.type="text/javascript";k.async=!0;k.src=l+"/widget-send-button/js/init.js";k.onload=function(){WhWidgetSendButton.init("getbutton.io",h,g)};l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(k,l)})()};
